const utils = require('./utils');

/////////////* DRAGONBORN */////////////

// FEMALE
const femaleDragonbornNames = [
  "Kathyra",
  "Aririth",
  "Welsidalynn",
  "Orikaryn",
  "Ocys",
  "Lilorinn",
  "Belwyn",
  "Kothibra",
  "Hinvyre",
  "Ariqorel",
  "Ophiriel",
  "Irlyfyire",
  "Vyraxora",
  "Qiwyn",
  "Someila",
  "Valxiris",
  "Wravyre",
  "Thapora",
  "Jocys",
  "Fenyassa",
  "Mirina",
  "Dafaeth",
  "Malqwen",
  "Quilliann",
  "Irlythyra",
  "Yrdalynn",
  "Jowyn",
  "Kahime",
  "Nyszys",
  "Yazita",
  "Wrawophyl",
  "Micoria",
  "Erlibith",
  "Therlarys",
  "Quilvyre",
  "Xyliann",
  "Perrinn",
  "Faesira",
  "Gurrinn",
  "Navyre",
  "Nyswophyl",
  "Ophigil",
  "Qirith",
  "Grixora",
  "Beldrish",
  "Zoffaeth",
  "Yrfyire",
  "Iriegil",
  "Nayassa",
  "Raivyre",
  "Gurdrith",
  "Nysthyra",
  "Sogwen",
  "Ophihymm",
  "Arisira",
  "Hinkira",
  "Fensira",
  "Gurlyassa",
  "Zofhime",
  "Welsilyassa"
];

// MALE
const maleDragonbornNames = [
  "Narvull",
  "Urobroth",
  "Qelziros",
  "Caerbarum",
  "Wurakas",
  "Lorxan",
  "Erasashi",
  "Narwunax",
  "Prikax",
  "Yorhadur",
  "Sahazar",
  "Totrin",
  "Yorqrin",
  "Hiciar",
  "Morprax",
  "Brendaar",
  "Calusashi",
  "Hiturim",
  "Medqrin",
  "Prirash",
  "Sulkul",
  "Dofarn",
  "Ghelin",
  "Lorhadur",
  "Lumilin",
  "Babor",
  "Worqrin",
  "Jardorim",
  "Ghejhan",
  "Wulythas",
  "Jarziros",
  "Wuskan",
  "Tobor",
  "Frowarum",
  "Calurinn",
  "Mednaar",
  "Iornaar",
  "Tosashi",
  "Wraskan",
  "Saxiros",
  "Zrazavur",
  "Worvarax",
  "Faerciar",
  "Aligar",
  "Pajurn",
  "Donaar",
  "Yorxan",
  "Uronaar",
  "Otihazar",
  "Kilziros",
  "Durwunax",
  "Gorabarum",
  "Rhohadur",
  "Brenciar",
  "Jarhazar",
  "Vorbroth",
  "Durzire",
  "Qelrash",
  "Orlaseth",
  "Faerbarum"
];

// SURNAME
const dragonbornSurnames = [
  "Clenxec",
  "Aldexish",
  "Criracnellas",
  "Driccankear",
  "Luthtan",
  "Onkuak",
  "Yerthikal",
  "Amtundiath",
  "Valthialirran",
  "Cuuldracnin",
  "Machid",
  "Clurdolith",
  "Ualmes",
  "Giltedergeth",
  "Myirak",
  "Kancaled",
  "Liankenthirgac",
  "Cimtoc",
  "Uumpajic",
  "Nurdesadaan",
  "Krerjac",
  "Myeaphotid",
  "Tampan",
  "Muathtaakosh",
  "Myelriastandon",
  "Nupeth",
  "Droconshtejuul",
  "Myemrindaluc",
  "Yimrac",
  "Dremrinshtac",
  "Yempinshtanduc",
  "Meaxus",
  "Yalthokomes",
  "Estun",
  "Clemmesh",
  "Keltocnojesh",
  "Iancaduullan",
  "Culdocnad",
  "Nistinkardaad",
  "Cimphonshtijel",
  "Uldrush",
  "Empokmis",
  "Deldaac",
  "Yimbaankijiath",
  "Yamphakmudias",
  "Krestinthirith",
  "Nyistar",
  "Varicnurrin",
  "Clulxianshteth",
  "Caldacollil",
  "Meccic",
  "Kammesh",
  "Altiastan",
  "Sharjeler",
  "Empon",
  "Nyulkendrarguash",
  "Clonkucnan",
  "Kelmores",
  "Myecek",
  "Apitiris"
];


/////////////* DWARF */////////////

// FEMALE
const femaleDwarfNames = [
  "Amber",
  "Artin",
  "Audhild",
  "Dagnal",
  "Eldeth",
  "Finellen",
  "Gunndola",
  "Gurdis",
  "Helja",
  "Kathra",
  "Ilde",
  "Kristryd",
  "Mardred",
  "Riswynn",
  "Torbera",
  "Vistra",
  "Sylveria",
  "Gronti"
];

// MALE
const maleDwarfNames = [
  "Nordak",
  "Olunt",
  "Kildrak",
  "Duergraf",
  "Adrik",
  "Baern",
  "Brottor",
  "Bruenor",
  "Fargrim",
  "Harberk",
  "Doran",
  "Travok",
  "Orsik",
  "Flint",
  "Rurik",
  "Thorin",
  "Ulfgar",
  "Vondal"
];

// SURNAME
const dwarfSurnames = [
  "Balderk",
  "Battlehammer",
  "Brawnanvil",
  "Dankil",
  "Fireforge",
  "Frostbeard",
  "Gorunn",
  "Ironfist",
  "Loderr",
  "Lutgehr",
  "Rumnaheim",
  "Torunn",
  "Ungart"
];


/////////////* ELF */////////////

// FEMALE
const femaleElfNames = [
  "Arara",
  "Amastrianna",
  "Antinua",
  "Birel",
  "Caelynn",
  "Chaedi",
  "Dara",
  "Drusilia",
  "Elama",
  "Enna",
  "Hatae",
  "Lelenia",
  "Keyleth",
  "Feyrre",
  "Melthrissa",
  "Aryana"
];

// MALE
const maleElfNames = [
  "Adran",
  "Aramil",
  "Austrin",
  "Erevan",
  "Fivin",
  "Galinndan",
  "Gennal",
  "Halimath",
  "Hiimo",
  "Immeral",
  "Korfel",
  "Lamlis",
  "Quarion",
  "Rolen",
  "Theren",
  "Theriatis",
  "Uthemar",
  "Tezoth",
  "Kaelthrimar",
  "Ardyn"
];

// SURNAME
const elfSurnames = [
  "Amakiir",
  "Caerdnel",
  "Casilltenirra",
  "Cithreth",
  "Mystralath",
  "Ofandrus",
  "Ostoroth",
  "Othronus",
  "Qualianthri",
  "Sylvaranth",
  "Raethran",
  "Liadon",
  "Lathalas",
  "Brightmoon",
  "Stargazer",
  "Moonbright",
  "Featherfall"
];


/////////////* GNOME */////////////

// FEMALE
const femaleGnomeNames = [
  "Vock",
  "Huck",
  "Zuth",
  "Nus",
  "Haxis",
  "Rulbush",
  "Ikzuth",
  "Utrothraim",
  "Zosuffosh",
  "Sensannailzish"
];

// MALE
const maleGnomeNames = [
  "Trutt",
  "Zod",
  "Cant",
  "Vriucdien",
  "Shmuakqa",
  "Puthatt",
  "Ivit",
  "Gobritan",
  "Kokruakrast",
  "Rarickembitt"
];

// SURNAME
const gnomeSurnames = [
  "Dodlawams",
  "Hasp",
  "Epswodnith",
  "Klippiesp",
  "Qrondiornficks",
  "Ter",
  "Pedomber",
  "Bems",
  "Uplizbiss",
  "Qagnom"
];


/////////////* HALF-ELF */////////////

// FEMALE
const femaleHalfElfNames = [
  "Edecharis",
  "Narue",
  "Emfine",
  "Mylnee",
  "Jehafarrel",
  "Inmadia",
  "Magkaala",
  "Gablossa",
  "Ylllaurel",
  "Tifziar"
];

// MALE
const maleHalfElfNames = [
  "Corrune",
  "Uldyr",
  "Iancraes",
  "Hilryn",
  "Urduin",
  "Nigemorn",
  "Eircraes",
  "Aalword",
  "Emeluin",
  "Dorlather"
];

// SURNAME
const halfElfSurnames = [
  "Caiqirelle",
  "Wynleth",
  "Elafiel",
  "Ololana",
  "Beikalyn",
  "Elaren",
  "Sarqirelle",
  "Faekian",
  "Lianan",
  "Luralei"
];


/////////////* HALF-ORC */////////////

// FEMALE
const femaleHalfOrcNames = [
  "Ruogra",
  "Zoca",
  "Geltah",
  "Rzuotto",
  "Vuhguo",
  "Kahro",
  "Rahgai",
  "Nulnaith",
  "Mimriblai",
  "Shunloto",
  "Ihenna",
  "Inifayt",
  "Kiska",
  "Megum",
  "Merifra",
  "Qezza",
  "Synas",
  "Tabba",
  "Talsa",
  "Tamert",
  "Flyana",
  "Gella",
  "Ghenna",
  "Ghisa",
  "Hedduga",
  "Hemta",
  "Henza",
  "Heznani",
  "Kanga",
  "Madmuna",
  "Melguma",
  "Mimasa",
  "Thasila",
  "Thazi",
  "Thizifa",
  "Thudja",
  "Tinsa",
  "Tlahra",
  "Uzifsula",
  "Zahoua",
];

// MALE
const maleHalfOrcNames = [
  "Gul",
  "Hrod",
  "Doch",
  "Purg",
  "Cer",
  "Patrul",
  "Zogdak",
  "Grubrol",
  "Crodhesk",
  "Botregrach",
  "Muaq",
  "Munaniq",
  "Naghi",
  "Oomos",
  "Patis",
  "Pianhol",
  "Taka",
  "Tuda",
  "Tukil",
  "Uirpok",
  "Arga",
  "Atalcas",
  "Atran",
  "Azous",
  "Badjena",
  "Beviki",
  "Bubul",
  "Crat",
  "Curriak",
  "Fild",
  "Ghan",
  "Glakpig",
  "Batsi",
  "Bekku",
  "Berin",
  "Derfor",
  "Elgal",
  "Gherzur"
];

// SURNAME
const halfOrcSurnames = [
  "Gud",
  "Orkuv",
  "Bon",
  "Cirelkev",
  "Kuk",
  "Atrix",
  "Jex",
  "Cumkix",
  "Wev",
  "Gnighadir",
  "Nubstar",
  "Thuld",
  "Rolm",
  "Shongalm",
  "Jer",
  "Shumke",
  "Matkaz",
  "Zar",
  "Vold",
  "Wughaz",
  "Gnev",
  "Gum",
  "Uvige",
  "Sarkid",
  "Noshky",
  "Vaz",
  "Theshky",
  "Raz",
  "Ilgro",
  "Kiresvro",
  "Thergo",
  "Bir",
  "Hunkur",
  "Tuloz",
  "Mashky",
  "Elraglok",
  "Zongi"
];


/////////////* HALFLING */////////////

// FEMALE
const femaleHalflingNames = [
  "Suseh",
  "Tavot",
  "Sira",
  "Wufo",
  "Wero",
  "Biolkalcul",
  "Fozulma",
  "Tulnurrath",
  "Vassezi",
  "Retiato",
  "Andry",
  "Bree",
  "Callie",
  "Cora",
  "Euphemia",
  "Jillian",
  "Kithri",
  "Lavinia",
  "Lidda",
  "Merla",
  "Nedda",
  "Paela",
  "Portia",
  "Seraphina",
  "Shaena",
  "Trym",
  "Vani",
  "Verna"
];

// MALE
const maleHalflingNames = [
  "Lal",
  "Dar",
  "Dord",
  "Ximoth",
  "Morrith",
  "Vruraard",
  "Turind",
  "Trasgaantard",
  "Hedirrorn",
  "Sarromrir",
  "Alton",
  "Ander",
  "Cade",
  "Corrin",
  "Eldon",
  "Errich",
  "Finnan",
  "Garret",
  "Lindal",
  "Lyle",
  "Merric",
  "Milo",
  "Osborn",
  "Perrin",
  "Reed",
  "Roscoe",
  "Wellby"
];

// SURNAME
const halflingSurnames = [
  "Featherheart",
  "Hogrirg",
  "Darkhelm",
  "Gnidliasrerd",
  "Softbranch",
  "Esiath",
  "Winterforce",
  "Kavu",
  "Humbleward",
  "Gliseanver",
  "Brushgather",
  "Goodbarrel",
  "Greenbottle",
  "High-hill",
  "Hilltopple",
  "Leagallow",
  "Tealeaf",
  "Thorngage",
  "Tosscobble",
  "Underbough"
];


/////////////* HUMAN */////////////

// FEMALE
const femaleHumanNames = [
  "Kum",
  "Miranda",
  "Sherrell",
  "Tyra",
  "Delma",
  "Eula",
  "Belkis",
  "Jennette",
  "Raelene",
  "Torrie",
  "Tressa",
  "Blanca",
  "Jerlene",
  "Jin",
  "Misti",
  "Sabra",
  "Anamaria",
  "Odilia",
  "Heide",
  "Golda",
  "Kendra",
  "Gertrudis",
  "Caterina",
  "Temika",
  "Waneta",
  "Lakenya",
  "Tatum",
  "Mitzie",
  "Sona",
  "Doria",
  "Rochell",
  "Genia",
  "Keren",
  "Latarsha",
  "Janee",
  "Chante",
  "Tamika",
  "Pura",
  "Caron",
  "Jasmine",
  "Dalia",
  "Jina",
  "Mitsue",
  "Yuette",
  "Lulu",
  "Shaina",
  "Quyen",
  "Zana",
  "Annamae",
  "Enola",
  "Shemeka",
  "Ami",
  "Buena",
  "Gaye",
  "Alane",
  "Marcelina",
  "Conception",
  "Francina",
  "Vernita",
  "Dinorah",
  "Tamiko",
  "Sonja",
  "Alayna",
  "Jannet",
  "Whitley",
  "Janina",
  "Eustolia",
  "Marvel",
  "Hien",
  "Georgine",
  "Joye",
  "Jolanda",
  "Olinda",
  "Kandi",
  "Ladonna",
  "Refugia",
  "Carmela",
  "Allegra",
  "Dinah",
  "Wendie",
  "Vonnie",
  "Elisa",
  "Joellen",
  "Sherril",
  "Larue",
  "Sunday",
  "Erica",
  "Shenna",
  "Antonietta",
  "Tonita",
  "Serafina",
  "Joselyn",
  "Ileen",
  "Kimiko",
  "Cassandra",
  "Kourtney",
  "Ginger",
  "Florene",
  "Kirsten",
  "Destiny",
  "Sarah",
  "Felica",
  "Sharen",
  "Milagro",
  "Audry",
  "Reyna",
  "Berenice",
  "Torie",
  "Caprice",
  "Aleshia",
  "Alanna",
  "Bong",
  "Tawna",
  "Lorna",
  "Maybelle",
  "Alease",
  "Shameka",
  "Olivia",
  "Noelle",
  "Kasandra",
  "Bridgett",
  "Luetta",
  "Lakeesha",
  "Isabella",
  "Annita",
  "Casimira",
  "Kali",
  "Dominica",
  "Tien",
  "Euna",
  "Jeanett",
  "Stephnie",
  "Malinda",
  "Shantae",
  "Shonda",
  "Shalonda",
  "Jami",
  "Shamika",
  "Aurora",
  "Belva",
  "Lavonia",
  "Shella",
  "Flossie",
  "Oretha",
  "Elza",
  "Veta",
  "Apryl",
  "Jayme"
];

// MALE
const maleHumanNames = [
  "Emmitt",
  "Shane",
  "Leonel",
  "Rob",
  "Numbers",
  "Dee",
  "Barton",
  "Rueben",
  "Josh",
  "Augustine",
  "Lynwood",
  "Blaine",
  "Keenan",
  "Kelvin",
  "Jonathon",
  "Jed",
  "Pablo",
  "Milton",
  "Fidel",
  "Quinn",
  "Steven",
  "Blair",
  "Norbert",
  "Antione",
  "Elijah",
  "Sammy",
  "Marc",
  "Waylon",
  "Chong",
  "Tobias",
  "Sheldon",
  "Burl",
  "Chris",
  "Gale",
  "Malcolm",
  "Mervin",
  "Danial",
  "Elvin",
  "Troy",
  "Royce",
  "Leon",
  "Clifford",
  "Boris",
  "Rufus",
  "Myron",
  "Johnathon",
  "Lamar",
  "Broderick",
  "Clinton",
  "Franklyn",
  "Elias",
  "Nick",
  "Efren",
  "Osvaldo",
  "Chang",
  "Dario",
  "Lance",
  "Zachary",
  "Lawerence",
  "Sterling",
  "Mel",
  "Russell",
  "Enoch",
  "Darnell",
  "Deangelo",
  "Luther",
  "Tyrone",
  "Steve",
  "Darrel",
  "Shaun",
  "Jonas",
  "Stuart",
  "Woodrow",
  "Cornelius",
  "Asa",
  "Theo",
  "Joey",
  "Alton",
  "Eduardo",
  "Cary",
  "Pete",
  "Odell",
  "Deshawn",
  "Sanford",
  "Ben",
  "Lonnie",
  "Brendan",
  "Gayle",
  "Rashad",
  "Wilbert",
  "Reggie",
  "Emanuel",
  "Everette",
  "Jorge",
  "Kirby",
  "Jody",
  "Galen",
  "Elden",
  "Rey",
  "Toney",
  "Mauro",
  "Arthur",
  "Hal",
  "Andrew",
  "Jame",
  "Kraig",
  "Ramiro",
  "Blake",
  "Alexander",
  "Grover",
  "Werner",
  "Damien",
  "Heath",
  "Britt",
  "Connie",
  "Wilber",
  "Tony",
  "Simon",
  "Beau",
  "Kip",
  "Christoper",
  "Curtis",
  "Santo",
  "Carmelo",
  "Denny",
  "Norman",
  "Kurt",
  "Lorenzo",
  "Elliott",
  "Mitchel",
  "Lynn",
  "Phillip",
  "Wes",
  "Rudolf",
  "Vincenzo",
  "Leif",
  "Ashley",
  "Clemente",
  "Ward",
  "Theodore",
  "Phil",
  "Otis",
  "Chuck",
  "Johnie",
  "Bradley",
  "Desmond",
  "Noah",
  "Aurelio",
  "Esteban"
];

// SURNAME
const humanSurnames = [
  "Huie",
  "Mchenry",
  "Gebhard",
  "Pedrosa",
  "Lazar",
  "Pembleton",
  "Mailloux",
  "Baron",
  "Ohern",
  "Smidt",
  "Mumma",
  "Macon",
  "Bauman",
  "Carrel",
  "Royalty",
  "Edwards",
  "Forward",
  "Dollar",
  "Pahl",
  "Kail",
  "Reece",
  "Prosser",
  "Beans",
  "Stoneburner",
  "Kehoe",
  "Mundell",
  "Wilbur",
  "Knoles",
  "Brookman",
  "Thoman",
  "Statler",
  "Goldschmidt",
  "Rapier",
  "Roseborough",
  "Cha",
  "Tafoya",
  "Birdsall",
  "Astudillo",
  "Mcateer",
  "Mcgrane",
  "Fischer",
  "Spicer",
  "Calabro",
  "Pilla",
  "Portner",
  "Pozo",
  "Rondeau",
  "Spray",
  "Cronin",
  "Cifuentes",
  "Bopp",
  "Jess",
  "Adan",
  "Buchanan",
  "Finklea",
  "Luebbers",
  "Risko",
  "Bird",
  "Siemens",
  "Urenda",
  "Bourbon",
  "Corl",
  "Estridge",
  "Mclawhorn",
  "Covington",
  "Mealer",
  "Huppert",
  "Simms",
  "Tindal",
  "Corkill",
  "Lemieux",
  "Reasor",
  "Varghese",
  "Worth",
  "Tansey",
  "Cameron",
  "Wickens",
  "Melson",
  "Lauderdale",
  "Follmer",
  "Gravel",
  "Napoles",
  "Marson",
  "Frasure",
  "Fang",
  "Boniello",
  "Joe",
  "Ozment",
  "Cuesta",
  "Araya",
  "Saul",
  "Axtell",
  "Penwell",
  "Teixeira",
  "Gebhart",
  "Dogan",
  "Abeita",
  "Maupin",
  "Osorio",
  "Wirth",
  "Bernstein",
  "Frey",
  "Waid",
  "Desousa",
  "Burchfield",
  "Demartino",
  "Gisi",
  "Janecek",
  "Murtha",
  "Dickerson",
  "Coaxum",
  "Thiede",
  "Poplawski",
  "Wiemer",
  "Passman",
  "Kiker",
  "Kolb",
  "Schmitmeyer",
  "Larusso",
  "Old",
  "Salvador",
  "Franson",
  "Kondo",
  "Monger",
  "Fales",
  "Bourgault",
  "Lamon",
  "Mccurry",
  "Mickles",
  "Jeppson",
  "Sansom",
  "Moisan",
  "Gardner",
  "Dargie",
  "Cracraft",
  "Gibeault",
  "Novotny",
  "Gimbel",
  "Dahm",
  "Drees",
  "Luter",
  "Skeen",
  "Bradeen",
  "Crook",
  "Maestas",
  "Chiesa",
  "Leverich",
  "Casperson",
  "Bettis",
  "Funes",
  "Slawson",
  "Edsall",
  "Creekmore",
  "Okelley",
  "Helgren",
  "Overfield",
  "Wemmer",
  "Demaree",
  "Machado",
  "Christensen",
  "Hefley",
  "Baumert",
  "Blaine",
  "Hamon",
  "Worthley",
  "Parodi",
  "Lesko",
  "Flannagan",
  "Bartling",
  "Piermarini",
  "Moncrief",
  "Duden",
  "Junk",
  "Hollie",
  "Rayburn",
  "Eastwood",
  "Widener",
  "Buss",
  "Hillebrand",
  "Anchondo",
  "Lopp",
  "Ketter",
  "Mongillo",
  "Chunn",
  "Galindo",
  "Michener",
  "Scarborough",
  "Biron",
  "Carlen",
  "Oldfield",
  "Prasad",
  "Mynatt",
  "Napoli",
  "Ogren",
  "Fleet",
  "Fassett",
  "Mcwhirter",
  "Saner",
  "Rohe",
  "Farris",
  "Ferranti",
  "Heisey",
  "Eck",
  "Dement",
  "Wnuk",
  "Kochan",
  "Hosey",
  "Bonnet",
  "Richert",
  "Munden",
  "Wurth",
  "Whisenhunt",
  "Mansfield",
  "Steed",
  "Fluellen",
  "Corn",
  "Messner",
  "Loder",
  "Haverland",
  "Hieber",
  "Odom",
  "Tarango",
  "Xie",
  "Cardinal",
  "Hermansen",
  "Fowler",
  "Carnley",
  "Cerrato",
  "Prentiss",
  "Fuhr",
  "Devaughn",
  "Milner",
  "Sharpless",
  "Donathan",
  "Jeske",
  "Hurla",
  "Neeson",
  "Birkhead",
  "Nathan",
  "Moriarty",
  "Vose",
  "Iacovelli",
  "Casanova",
  "Schoenfeld",
  "Lenz",
  "Lasley",
  "Rolan",
  "Bowley",
  "Ellsworth",
  "Patchell",
  "Quintero",
  "Donaldson",
  "Chevez",
  "Magruder",
  "Behringer",
  "Husman",
  "Crenshaw",
  "Fenwick",
  "Pigg",
  "Gandy",
  "Liming",
  "Candanoza",
  "Weisinger",
  "Gloor",
  "Arnone",
  "Chaudhry",
  "Jacobsen",
  "Goss",
  "Pafford",
  "Carlino",
  "Fall",
  "Donati",
  "Blough",
  "Roundtree",
  "Hyland",
  "Deltoro",
  "Montufar",
  "Kornegay",
  "Welles",
  "Koval",
  "Meyers",
  "Townsel",
  "Wicklund",
  "Officer",
  "Savoy",
  "Viggiano",
  "Well",
  "Scales",
  "Beauvais",
  "Artist",
  "Doerr",
  "Petit",
  "Anglin",
  "Leaman",
  "Zynda",
  "Bardsley",
  "Mascia"
];


/////////////* TIEFLING */////////////

// FEMALE
const femaleTieflingNames = [
  "Zecria",
  "Seiricyra",
  "Fririssa",
  "Eaxori",
  "Afspira",
  "Briwala",
  "Lewala",
  "Faith",
  "Journey",
  "Levdani",
  "Levrali",
  "Yapione",
  "Dimzes",
  "Kalrali",
  "Pheborys",
  "Yorasolis",
  "Interesting",
  "Song",
  "Darkness",
  "Zaseis",
  "Nithki",
  "Kalmaia",
  "Yorabis",
  "Pespunith",
  "Zaipunith",
  "Levyis",
  "Timeless",
  "Gloom",
  "Chant",
  "Stresral",
  "Lennel",
  "Shosith",
  "Valdin",
  "Thilah",
  "Thorzendes",
  "Khordradrel",
  "Savreimsen",
  "Lerototh",
  "Neneyin"
];

// MALE
const maleTieflingNames = [
  "Hormos",
  "Nephrut",
  "Malvir",
  "Valrus",
  "Uriira",
  "Karai",
  "Lokelech",
  "Eternal",
  "Rolnon",
  "Valthus ",
  "Meichar",
  "Thynemenos",
  "Kilrus",
  "Xarmos",
  "Dharron",
  "Salrius",
  "Valakas",
  "Zhermos",
  "Malenon",
  "Zorlius ",
  "Barilius",
  "Mavchar",
  "Nephmeros",
  "Killius",
  "Ekreus",
  "Carlech",
  "Arrai ",
  "Dokuc",
  "Yinry",
  "Adriath",
  "Yicor",
  "Zusuc",
  "Areci",
  "Agecus",
  "Elladrun",
  "Hilliardan",
  "Ertiallat"
];

// SURNAME
const tieflingSurnames = [
  "Vervend ",
  "Brotaebae ",
  "Tovos ",
  "Zegraki ",
  "Shama ",
  "Toldris ",
  "Rova ",
  "Ecorvot ",
  "Drardim ",
  "Shagrerat ",
  "Mokot ",
  "Nirvad ",
  "Sashakeand ",
  "Fondre ",
  "Letevri ",
  "Veni ",
  "Gibon",
  "Dobramia",
  "Nende",
  "Zetedaand",
  "Harvo",
  "Pasrossa",
  "Abem",
  "Riavagrat",
  "Fommeld",
  "Drorhiki"
];



/////////////* SWITCH FUNCTION */////////////



function returnRandomName(character) {
  switch (true) {
    case character.race === "dragonborn" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleDragonbornNames);
      character.lastName = utils.returnRandomArrayItem(dragonbornSurnames);
      break;
    case character.race === "dragonborn" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleDragonbornNames);
      character.lastName = utils.returnRandomArrayItem(dragonbornSurnames);
      break;

    case character.race === "dwarf" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleDwarfNames);
      character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
      break;
    case character.race === "dwarf" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleDwarfNames);
      character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
      break;

    case character.race === "elf" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleElfNames);
      character.lastName = utils.returnRandomArrayItem(elfSurnames);
      break;
    case character.race === "elf" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleElfNames);
      character.lastName = utils.returnRandomArrayItem(elfSurnames);
      break;

    case character.race === "gnome" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleGnomeNames);
      character.lastName = utils.returnRandomArrayItem(gnomeSurnames);
      break;
    case character.race === "gnome" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleGnomeNames);
      character.lastName = utils.returnRandomArrayItem(gnomeSurnames);
      break;

    case character.race === "half-elf" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleHalfElfNames);
      character.lastName = utils.returnRandomArrayItem(halfElfSurnames);
      break;
    case character.race === "half-elf" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleHalfElfNames);
      character.lastName = utils.returnRandomArrayItem(halfElfSurnames);
      break;

    case character.race === "half-orc" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleHalfOrcNames);
      character.lastName = utils.returnRandomArrayItem(halfOrcSurnames);
      break;
    case character.race === "half-orc" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleHalfOrcNames);
      character.lastName = utils.returnRandomArrayItem(halfOrcSurnames);
      break;

    case character.race === "halfling" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleHalflingNames);
      character.lastName = utils.returnRandomArrayItem(halflingSurnames);
      break;
    case character.race === "halfling" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleHalflingNames);
      character.lastName = utils.returnRandomArrayItem(halflingSurnames);
      break;

    case character.race === "human" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleHumanNames);
      character.lastName = utils.returnRandomArrayItem(humanSurnames);
      break;
    case character.race === "human" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleHumanNames);
      character.lastName = utils.returnRandomArrayItem(humanSurnames);
      break;

    case character.race === "tiefling" && character.gender === "male":
      character.firstName = utils.returnRandomArrayItem(maleTieflingNames);
      character.lastName = utils.returnRandomArrayItem(tieflingSurnames);
      break;
    case character.race === "tiefling" && character.gender === "female":
      character.firstName = utils.returnRandomArrayItem(femaleTieflingNames);
      character.lastName = utils.returnRandomArrayItem(tieflingSurnames);
      break;

    default: character.firstName = "James"; character.lastName = "Bond";
  }

  return character;
}

exports.returnRandomName = returnRandomName;
