function getRandomNumber(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomItem(collection) {
  index = getRandomNumber(0, collection.length - 1);
  return collection[index];
}

generalDescriptions = [
  "able",
  "abnormal",
  "absent-minded",
  "above average",
  "adventurous",
  "affectionate",
  "agile",
  "agreeable",
  "alert",
  "amazing",
  "ambitious",
  "amiable",
  "amusing",
  "analytical",
  "angelic",
  "apathetic",
  "apprehensive",
  "ardent",
  "artificial",
  "artistic",
  "assertive",
  "attentive",
  "average",
  "awesome",
  "awful",
  "balanced",
  "beautiful",
  "below average",
  "beneficent",
  "blue",
  "blunt",
  "boisterous",
  "brave",
  "bright",
  "brilliant",
  "buff",
  "callous",
  "candid",
  "cantankerous",
  "capable",
  "careful",
  "careless",
  "caustic",
  "cautious",
  "charming",
  "childish",
  "childlike",
  "cheerful",
  "chic",
  "churlish",
  "circumspect",
  "civil",
  "clean",
  "clever",
  "clumsy",
  "coherent",
  "cold",
  "competent",
  "composed",
  "conceited",
  "condescending",
  "confident",
  "confused",
  "conscientious",
  "considerate",
  "content",
  "cool",
  "cool-headed",
  "cooperative",
  "cordial",
  "courageous",
  "cowardly",
  "crabby",
  "crafty",
  "cranky",
  "crass",
  "critical",
  "cruel",
  "curious",
  "cynical",
  "dainty",
  "decisive",
  "deep",
  "deferential",
  "deft",
  "delicate",
  "demonic",
  "dependent",
  "delightful",
  "demure",
  "depressed",
  "devoted",
  "dextrous",
  "diligent",
  "direct",
  "dirty",
  "disagreeable",
  "discerning",
  "discreet",
  "disruptive",
  "distant",
  "distraught",
  "distrustful",
  "dowdy",
  "dramatic",
  "dreary",
  "drowsy",
  "drugged",
  "drunk",
  "dull",
  "dutiful",
  "eager",
  "earnest",
  "easy-going",
  "efficient",
  "egotistical",
  "elfin",
  "emotional",
  "energetic",
  "enterprising",
  "enthusiastic",
  "evasive",
  "even-tempered",
  "exacting",
  "excellent",
  "excitable",
  "experienced",
  "fabulous",
  "fastidious",
  "ferocious",
  "fervent",
  "fiery",
  "flabby",
  "flaky",
  "flashy",
  "frank",
  "friendly",
  "funny",
  "fussy",
  "generous",
  "gentle",
  "gloomy",
  "glutinous",
  "good",
  "grave",
  "great",
  "groggy",
  "grouchy",
  "guarded",
  "hateful",
  "hearty",
  "helpful",
  "hesitant",
  "hot-headed",
  "hypercritical",
  "hysterical",
  "idiotic",
  "idle",
  "illogical",
  "imaginative",
  "immature",
  "immodest",
  "impatient",
  "imperturbable",
  "impetuous",
  "impractical",
  "impressionable",
  "impressive",
  "impulsive",
  "inactive",
  "incisive",
  "incompetent",
  "inconsiderate",
  "inconsistent",
  "independent",
  "indiscreet",
  "indolent",
  "indefatigable",
  "industrious",
  "inexperienced",
  "insensitive",
  "inspiring",
  "intelligent",
  "interesting",
  "intolerant",
  "inventive",
  "irascible",
  "irritable",
  "irritating",
  "jocular",
  "jovial",
  "joyous",
  "judgmental",
  "keen",
  "kind",
  "lame",
  "lazy",
  "lean",
  "leery",
  "lethargic",
  "level-headed",
  "listless",
  "lithe",
  "lively",
  "local",
  "logical",
  "long-winded",
  "lovable",
  "love-lorn",
  "lovely",
  "maternal",
  "mature",
  "mean",
  "meddlesome",
  "mercurial",
  "methodical",
  "meticulous",
  "mild",
  "miserable",
  "modest",
  "moronic",
  "morose",
  "motivated",
  "musical",
  "naive",
  "nasty",
  "natural",
  "naughty",
  "negative",
  "nervous",
  "noisy",
  "normal",
  "nosy",
  "numb",
  "obliging",
  "obnoxious",
  "old-fashioned",
  "one-sided",
  "orderly",
  "ostentatious",
  "outgoing",
  "outspoken",
  "passionate",
  "passive",
  "paternal",
  "paternalistic",
  "patient",
  "peaceful",
  "peevish",
  "pensive",
  "persevering",
  "persnickety",
  "petulant",
  "picky",
  "plain",
  "plain-speaking",
  "playful",
  "pleasant",
  "plucky",
  "polite",
  "popular",
  "positive",
  "powerful",
  "practical",
  "prejudiced",
  "pretty",
  "proficient",
  "proud",
  "provocative",
  "prudent",
  "punctual",
  "quarrelsome",
  "querulous",
  "quick",
  "quick-tempered",
  "quiet",
  "realistic",
  "reassuring",
  "reclusive",
  "reliable",
  "reluctant",
  "resentful",
  "reserved",
  "resigned",
  "resourceful",
  "respected",
  "respectful",
  "responsible",
  "restless",
  "revered",
  "ridiculous",
  "sad",
  "sassy",
  "saucy",
  "sedate",
  "self-assured",
  "selfish",
  "sensible",
  "sensitive",
  "sentimental",
  "serene",
  "serious",
  "sharp",
  "short-tempered",
  "shrewd",
  "shy",
  "silly",
  "sincere",
  "sleepy",
  "slight",
  "sloppy",
  "slothful",
  "slovenly",
  "slow",
  "smart",
  "snazzy",
  "sneering",
  "snobby",
  "somber",
  "sober",
  "sophisticated",
  "soulful",
  "soulless",
  "sour",
  "spirited",
  "spiteful",
  "stable",
  "staid",
  "steady",
  "stern",
  "stoic",
  "striking",
  "strong",
  "stupid",
  "sturdy",
  "subtle",
  "sullen",
  "sulky",
  "supercilious",
  "superficial",
  "surly",
  "suspicious",
  "sweet",
  "tactful",
  "tactless",
  "talented",
  "testy",
  "thinking",
  "thoughtful",
  "thoughtless",
  "timid",
  "tired",
  "tolerant",
  "touchy",
  "tranquil",
  "ugly",
  "unaffected",
  "unbalanced",
  "uncertain",
  "uncooperative",
  "undependable",
  "unemotional",
  "unfriendly",
  "unguarded",
  "unhelpful",
  "unimaginative",
  "unmotivated",
  "unpleasant",
  "unpopular",
  "unreliable",
  "unsophisticated",
  "unstable",
  "unsure",
  "unthinking",
  "unwilling",
  "venal",
  "versatile",
  "vigilant",
  "warm",
  "warmhearted",
  "wary",
  "watchful",
  "weak",
  "well-behaved",
  "well-developed",
  "well-intentioned",
  "well-respected",
  "well-rounded",
  "willing",
  "wonderful",
  "volcanic",
  "vulnerable",
  "zealous"
];

const colours = [
  "White",
  "Yellow",
  "Blue",
  "Red",
  "Green",
  "Black",
  "Brown",
  "Azure",
  "Ivory",
  "Teal",
  "Silver",
  "Purple",
  "Navy blue",
  "Pea green",
  "Gray",
  "Orange",
  "Maroon",
  "Charcoal",
  "Aquamarine",
  "Coral",
  "Fuchsia",
  "Wheat",
  "Lime",
  "Crimson",
  "Khaki",
  "Hot pink",
  "Magenta",
  "Olden",
  "Plum",
  "Olive",
  "Cyan"
];

const hairLengths = [
  "ear length",
  "chin length",
  "neck length",
  "shoulder length",
  "collarbone length",
  "armpit length",
  "mid-back length",
  "hip length",
  "tailbone length",
  "mid thigh length",
  "knee length",
  "calf length",
  "ankle length"
];

const hairStyles = [
  "Afro",
  "Asymmetric cut",
  "Beehive",
  "Bangs",
  "Bob cut",
  "Bouffant",
  "Bowl cut",
  "Braid",
  "Bun",
  "Bunches",
  "Butch cut",
  "Buzz cut",
  "Comb over",
  "Double buns",
  "Dreadlocks",
  "French braid",
  "Ponytail",
  "Rattail",
  "top Knot",
  "undercut"
];

const facialHair = [
  "Beard",
  "Chinstrap",
  "Goatee",
  "Soul patch",
  "Van Dyke",
  "moustache",
  "Fu Manchu Moustache",
  "handlebar Moustache",
  "horseshoe Moustache",
  "pencil Moustache",
  "toothbrush Moustache",
  "walrus Moustache",
  "Designer stubble",
  "Sideburns"
];

const generalSizes = ["tiny", "small", "medium", "large", "huge"];

const sizeAdjectives = [
  "baby",
  "illimitable",
  "scrawny",
  "beefy",
  "immeasurable",
  "short",
  "big",
  "immense",
  "sizable",
  "bony",
  "infinitesimal",
  "skeletal",
  "boundless",
  "lanky",
  "skimpy",
  "brawny",
  "large",
  "skinny",
  "broad",
  "lean",
  "slender",
  "bulky",
  "life-size",
  "slim",
  "chunky",
  "limitless",
  "small",
  "colossal",
  "little",
  "squat",
  "compact",
  "mammoth",
  "stocky",
  "corpulent",
  "massive",
  "stout",
  "cosmic",
  "meager",
  "strapping",
  "cubby",
  "measly",
  "sturdy",
  "curvy",
  "microscopic",
  "tall",
  "elfin",
  "mini",
  "teensy",
  "emaciated",
  "miniature",
  "teeny",
  "endless",
  "minuscule",
  "teeny-tiny",
  "enormous",
  "minute",
  "teeny-weeny",
  "epic",
  "narrow",
  "thick",
  "expansive",
  "obese",
  "thickset",
  "extensive",
  "outsized",
  "thin",
  "fat",
  "oversize",
  "tiny",
  "fleshy",
  "overweight",
  "titanic",
  "full-size",
  "paltry",
  "towering",
  "gargantuan",
  "petite",
  "trifling",
  "gaunt",
  "pint-size",
  "trim",
  "giant",
  "plump",
  "tubby",
  "gigantic",
  "pocket-size",
  "undersized",
  "grand",
  "portly",
  "underweight",
  "great",
  "pudgy",
  "unlimited",
  "heavy",
  "puny",
  "vast",
  "hefty",
  "rotund",
  "wee",
  "huge",
  "scanty",
  "whopping",
  "hulking",
  "scraggy",
  "wide"
];

const occupation = [
  "Actor",
  "Lawyer",
  "Alchemist",
  "Animal Handler",
  "Apothecary",
  "Architect",
  "Archer",
  "Archivist",
  "Aristocrat",
  "Armorer",
  "Artisan",
  "Artist",
  "Astrologer",
  "Baker",
  "Banker",
  "Barbarian",
  "Barber",
  "Bard",
  "Barkeep",
  "Barmaid",
  "Beekeeper",
  "Beer",
  "Seller",
  "Beggar",
  "Blacksmith",
  "Boatman",
  "Bookbinder",
  "Bookseller",
  "Brewer",
  "Bricklayer",
  "Brick Maker",
  "Brigand",
  "Brothel Keeper",
  "Buckle Maker",
  "Builder",
  "Butcher",
  "Caravan Leader",
  "Carpenter",
  "Cartographer",
  "Chandler",
  "Charioteer",
  "Chatelaine",
  "Chef",
  "Chieftain",
  "Chirurgeon",
  "Clergyman",
  "Clerk",
  "Clock Maker",
  "Clothworker",
  "Cobbler",
  "Commander",
  "Concubine",
  "Cook",
  "Cooper",
  "Copyist",
  "Costermonger",
  "Counselor",
  "Courtesan",
  "Courtier",
  "Cowherd",
  "Crossbowman",
  "Cutler",
  "Daimyo",
  "Dairymaid",
  "Dancer",
  "Diplomat",
  "Distiller",
  "Diver",
  "Diviner",
  "Doctor",
  "Domestic Servant",
  "Eunuch",
  "Explorer",
  "Farmer",
  "Fighter",
  "Fisherman",
  "Fishmonger",
  "Footman",
  "Furrier",
  "Galley Slave",
  "Gardener",
  "Geisha",
  "General",
  "Gladiator",
  "Glovemaker",
  "Goldsmith",
  "Grocer",
  "Groom",
  "Guardsman",
  "Guildmaster",
  "Harness maker",
  "Hatmaker",
  "Hay merchant",
  "Healer",
  "Herald",
  "Herbalist",
  "Herder",
  "Hermit",
  "Highwayman",
  "Historian",
  "Housemaid",
  "Hunter",
  "Illuminator",
  "Infantryman",
  "Innkeeper",
  "Interpreter",
  "Inventor",
  "Jailer",
  "Jester",
  "Jeweler",
  "Jongleur",
  "Judge",
  "Kitchen drudge",
  "Knight",
  "Laborer",
  "Lady	Lady in Waiting",
  "Leatherworker",
  "Librarian",
  "Linguist",
  "Locksmith",
  "Longbowman",
  "Longshoreman",
  "Maidservant",
  "Man at Arms",
  "Mason",
  "Masseur",
  "Mayor",
  "Mercer",
  "Merchant",
  "Messenger",
  "Midwife",
  "Miller",
  "Miner",
  "Minister",
  "Minstrel",
  "Monk",
  "Mortician",
  "Mourner",
  "Musician",
  "Necromancer",
  "Noble",
  "Nun",
  "Nurse",
  "Old-clothes seller",
  "Page",
  "Painter",
  "Pariah",
  "Pastry cook",
  "Peasant",
  "Perfumer",
  "Philosopher",
  "Physician",
  "Pigkeeper",
  "Pilgrim",
  "Pirate",
  "Plasterer",
  "Potter",
  "Priestess",
  "Princess",
  "Privateer",
  "Professor",
  "Prostitute",
  "Pursemaker",
  "Queen",
  "Ranger",
  "Ratcatcher",
  "Reeve",
  "Ronin",
  "Roofer",
  "Ropemaker",
  "Royal",
  "Adviser",
  "Rugmaker",
  "Ruler",
  "Saddler",
  "Sailor",
  "Samurai",
  "Scabbard maker",
  "Sculptor",
  "Scavenger",
  "Scholar",
  "Scrivener",
  "Seamstress",
  "Servant",
  "Shaman",
  "Shepherd",
  "Ship's captain",
  "Shoemaker",
  "Silversmith",
  "Slave",
  "Slaver",
  "Smith",
  "Soldier",
  "Sorcerer",
  "Sorceress",
  "Spice Merchant",
  "Squire",
  "Stablehand",
  "Stevedore",
  "Stonemason",
  "Storyteller",
  "Steward",
  "Street kid",
  "Street seller",
  "Street sweeper",
  "Student",
  "Surgeon",
  "Surveyor",
  "Swordsman",
  "Sycophant",
  "Tailor",
  "Tanner",
  "Tavernkeeper",
  "Tax collector",
  "Teacher",
  "Teamster",
  "Thatcher",
  "Thief",
  "Tinker",
  "Torturer",
  "Town crier",
  "Toymaker",
  "Trapper",
  "Vendor",
  "Vermin catcher",
  "Veterinarian",
  "Village chief",
  "Vintner",
  "Viking",
  "Warlock",
  "Warrior",
  "Water carrier",
  "Weaver",
  "Wetnurse",
  "Wine seller",
  "Witch",
  "Wizard",
  "Woodcarver",
  "Woodcutter",
  "Wood seller",
  "Wrestler",
  "Writer"
];

const bodyParts = [
  "ankle",
  "arm",
  "back",
  "belly",
  "bottom",
  "breast",
  "buttocks",
  "calf",
  "cheek",
  "chin",
  "ear",
  "elbow",
  "eye",
  "eyebrow",
  "eyelash",
  "finger",
  "fist",
  "foot",
  "forearm",
  "forehead",
  "hair",
  "hand",
  "head",
  "hip",
  "knee",
  "leg",
  "lip",
  "lower leg",
  "mouth",
  "neck",
  "nose",
  "nostril",
  "shoulder",
  "thigh",
  "thumb",
  "toe",
  "tongue",
  "tooth",
  "upper arm",
  "waist",
  "wrist"
];

const clothes = [
  "baby grow",
  "ball gown",
  "belt",
  "bikini",
  "blazer",
  "blouse",
  "boots",
  "bow tie",
  "boxers",
  "bra",
  "bra & knicker set",
  "briefs",
  "camisole",
  "cap",
  "cardigan",
  "cargos",
  "catsuit",
  "chemise",
  "coat",
  "corset",
  "cravat",
  "cufflinks",
  "cummerbund",
  "dinner jacket",
  "dress",
  "dressing gown",
  "dungarees",
  "fleece",
  "gloves",
  "hat",
  "hoody",
  "jacket",
  "jeans",
  "jogging suit",
  "jumper",
  "kaftan",
  "kilt",
  "knickers",
  "kurta",
  "lingerie",
  "nightgown",
  "nightwear",
  "pants",
  "pashmina",
  "polo shirt",
  "poncho",
  "pyjamas",
  "raincoat",
  "robe",
  "romper",
  "sandals",
  "sarong",
  "scarf",
  "shawl",
  "shellsuit",
  "shirt",
  "shoes",
  "shorts",
  "skirt",
  "slacks",
  "slippers",
  "socks",
  "stockings",
  "suit",
  "sunglasses",
  "sweater",
  "sweatshirt",
  "swimming costume",
  "swimming shorts",
  "swimming trunks",
  "swimwear",
  "t-shirt",
  "tailcoat",
  "tankini",
  "thong",
  "tie",
  "tights",
  "top",
  "tracksuit",
  "trainers",
  "trousers",
  "underclothes",
  "underpants",
  "undershirt",
  "underwear",
  "vest",
  "vest underwear",
  "waistcoat",
  "waterproof",
  "zip"
];

function physicalAttributes() {
  this.hairColour = getRandomItem(colours);
  this.hairLength = getRandomItem(hairLengths);
  this.hairStyle = getRandomItem(hairStyles);
  this.eyeColour = getRandomItem(colours);
  this.facialHair = getRandomItem(facialHair);
  this.facialHairColour = getRandomItem(colours);
  this.eyeSize = getRandomItem(generalSizes);
  this.skinColour = getRandomItem(colours);
  this.armLength = getRandomItem(generalSizes);
  this.legLength = getRandomItem(generalSizes);
  this.facialExpression = getRandomItem(generalDescriptions);
  this.dreamOccupation = getRandomItem(occupation);
  this.favoriteItem = `${getRandomItem(colours)} ${getRandomItem(clothes)}`;
}

function physicalDescription(name, gender, race) {
  let x = new physicalAttributes();
  let description = [
    `${name} is a ${getRandomItem(generalSizes)} ${gender} ${
      x.skinColour
    } skinned ${race}. Their ${x.hairColour} coloured hair is styled in a ${
      x.hairLength
    } ${x.hairStyle}. They have ${x.eyeSize} ${
      x.eyeColour
    } coloured eyes that betray no thoughts. they have a ${getRandomItem(
      generalSizes
    )} ${x.facialHairColour} ${x.facialHair} that fits their ${
      x.facialExpression
    } facial expression well. they never leave home without their ${
      x.favoriteItem
    } and dream of one day becoming a ${x.dreamOccupation}`
  ];
  return description;
}

exports.physicalDescription = physicalDescription;
